language: python
python:
  - "2.7"


# command to install dependencies
install:
  - pip install behave
  - pip install allure-behave
# command to run tests
script:
  -sonar-scanner --Dsonar.projectKey=awt  -Dsonar.organization=awt-training -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
  -behave -f allure_behave.formatter:AllureFormatter -o %allure_result_folder%

addons:
  sonarcloud:
    organization: "awt-training"
    token:
      secure: $GITHUB_TOKEN



notifications:
 email: true
   - Bruno.Barrios@jalasoft.com
