language: python
python:
  - "2.7"


# command to install dependencies
install:
  - pip install behave
  - pip install allure-behave

# command to run tests
script:
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
  - behave -f allure_behave.formatter:AllureFormatter -o %allure_result_folder%

addons:
  sonarcloud:
    organization: "awt-01-training"
    token:
      secure: $SONAR_TOKEN



notifications:
 email: true
   - Bruno.Barrios@jalasoft.com
